title = Willkommen zu dieser test.
card-title = Hallo Welt
button-info = Mehr Infos
card-description = Dieses Kätzchen ist ebenso niedlich wie verspielt. Holen Sie ihn noch heute nach Hause!<br /><small>6 Wochen alt</small>
select-language = Wählen Sie Ihre Sprache:
sf = Hallo in San Francisco
jupyter = jupyter ist ein schöner Planet
how-weather = Heute ist ein heißer Tag in NYC.
fred = Hallo Fred, wie ist das Wetter in Großbritannien?
igor = Hallo Igor!
jupy = Jupyter-Notizbuch.
hell = Hallso ps
hehe = Hallso wihfaoinfsnio
charles = Hallo Charles, wie geht es dir morgen?
root = Hallo Root.vc
launchhouse = Ich bin bei LaunchHouse
add-basket = Korb hinzufügen
