title = Welcome this beautiful afternoon in SF.
card-title = Mittens
card-description = This kitten is as cute as he is playful. Bring him home today!<br /><small>6 weeks old</small>
button-info = More Info
select-language = Select your language:
sf = Hallo in New York
hehe = Hallso wihfaoinfsnio
hell = Hallso ps
jupyter = jupyter is a nice planet
how-weather = Today is a hot day in NYC.
david = Hi David!