title = Bienvenido a esta hermosa tarde en SF.
card-title = Mitones
card-description = Este gatito es tan bonito como juguetón. ¡Llévatelo a casa hoy mismo!<br /><small>6 semanas de edad</small>
select-language = Seleccione su idioma:
button-info = Más información
sf = Hallo en Nueva York
hello = Hola mundo 12345
hehe = Hallso wihfaoinfsnio
hell = Hallso ps
jupyter = jupyter es un bonito planeta
moritz = Hola Moritz
