title = Taco
card-title = Hola
button-info = Más información
card-description = Este gatito es tan bonito como juguetón. ¡Llévatelo a casa hoy mismo!<br /><small>6 semanas de edad</small>
select-language = Seleccione su idioma:
sf = Hallo en San Francisco
jupyter = jupyter es un bonito planeta
how-weather = Hoy es un día caluroso en NYC.
fred = Hola Fred, ¿cómo está el tiempo en el Reino Unido?
